# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  datasource:
    url: jdbc:mysql://111.173.80.149:3306/dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wh@942966
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      host: localhost
      port: 6379                 # Redis 端口
      timeout: 6000              # 连接超时时间
      lettuce:
        pool:
          max-active: 8          # 最大活跃连接数
          max-idle: 8            # 最大空闲连接数
          min-idle: 0            # 最小空闲连接数
          max-wait: -1ms         # 连接池最大阻塞等待时间

mybatis-plus:
  configuration:
    # 自动驼峰命名转换
    map-underscore-to-camel-case: true